### ISSUE TITLE
error

### ISSUE THREAD

**Issue by waltercruz** [solilokiam/SummernoteBundle#11]
sorry if this is not the best place to ask but I'm getting a error:

The function "form_stylesheet" does not exist. Did you mean "summernote_form_stylesheet" in SolilokiamSummernoteBundle:Form:summernotestylesheet.html.twig at line 4

**Comment by nursultanturdaliev** [comment]
Have you already solved this issue? I also had the same issue. 
Installing the  [GenemuFormBundle](https://github.com/genemu/GenemuFormBundle) should solve the issue. Because it has `form_stylesheet` extension. [Here](https://github.com/genemu/GenemuFormBundle/blob/master/Twig/Extension/FormExtension.php)

**Comment by solilokiam** [comment]
sorry this repository is no longer mantained. If you want you can fork and fix it if you want.
